spring.application.name=startsecure

spring.datasource.url=jdbc:postgresql://localhost:5432/startsecure
spring.datasource.username=startsecure_user

spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


#cognito

spring.security.oauth2.client.registration.cognito.scope=openid
spring.security.oauth2.client.provider.cognito.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_xMHarbJPv
aws.region=us-east-1


